import manifest from './icon-manifest.json';
import type { ServiceDef } from '@/lib/providers/types';

/**
 * Extended AWS catalog — every official AWS Architecture Icon as a draggable
 * palette service, so no AWS service icon is missing from the studio.
 *
 * The curated catalog (catalog.ts) stays the source for services with real
 * config fields + cost models, and it alone feeds the LLM planner via the
 * server registry (registry.ts) — these extended entries are palette/canvas
 * only, deliberately kept OUT of generation prompts so 250+ extra services
 * never compete for prompt space (memory: generation-quality focus).
 *
 * Entries are [icon file (no .svg), display name, category]. Accents come from
 * icon-manifest.json (the official category color baked into each icon), and
 * pricing is the same editable indicative monthly cost that AI-added dynamic
 * services use. tests/aws-icon-coverage.test.ts asserts the three lists below
 * (curated + skipped + extended) exactly cover public/icons/aws/svc.
 */

/** svc icons already represented by a curated catalog.ts service. */
export const CURATED_ICON_FILES: string[] = [
  'AmazonAPIGateway',
  'AmazonAthena',
  'AmazonAurora',
  'AmazonBedrock',
  'AmazonCloudFront',
  'AmazonCloudWatch',
  'AmazonCognito',
  'AmazonDynamoDB',
  'AmazonEC2',
  'AmazonEFS',
  'AmazonElastiCache',
  'AmazonElasticContainerRegistry',
  'AmazonElasticContainerService',
  'AmazonElasticKubernetesService',
  'AmazonEventBridge',
  'AmazonGuardDuty',
  'AmazonKinesis',
  'AmazonKinesisDataStreams',
  'AmazonManagedStreamingforApacheKafka',
  'AmazonOpenSearchService',
  'AmazonRDS',
  'AmazonRedshift',
  'AmazonRoute53',
  'AmazonSageMaker',
  'AmazonSimpleEmailService',
  'AmazonSimpleNotificationService',
  'AmazonSimpleQueueService',
  'AmazonSimpleStorageService',
  'AWSAppSync',
  'AWSBackup',
  'AWSBatch',
  'AWSCertificateManager',
  'AWSCloudTrail',
  'AWSConfig',
  'AWSFargate',
  'AWSGlue',
  'AWSIoTCore',
  'AWSKeyManagementService',
  'AWSLambda',
  'AWSSecretsManager',
  'AWSStepFunctions',
  'AWSWAF',
  'AWSXRay',
];

/** Deliberately not offered: theme variants, not distinct services. */
export const SKIPPED_ICON_FILES: string[] = ['AWSMarketplaceDark'];

/** [icon file, display name, category] for every remaining official icon. */
const EXTENDED: [string, string, string][] = [
  // ---- Compute ----
  ['AmazonEC2AutoScaling', 'EC2 Auto Scaling', 'Compute'],
  ['AmazonEC2ImageBuilder', 'EC2 Image Builder', 'Compute'],
  ['AmazonElasticVMwareService', 'Elastic VMware Service', 'Compute'],
  ['AmazonLightsail', 'Lightsail', 'Compute'],
  ['AmazonLightsailforResearch', 'Lightsail for Research', 'Compute'],
  ['AWSAppRunner', 'App Runner', 'Compute'],
  ['AWSElasticBeanstalk', 'Elastic Beanstalk', 'Compute'],
  ['AWSLocalZones', 'Local Zones', 'Compute'],
  ['AWSNitroEnclaves', 'Nitro Enclaves', 'Compute'],
  ['AWSOutpostsfamily', 'Outposts Family', 'Compute'],
  ['AWSOutpostsrack', 'Outposts Rack', 'Compute'],
  ['AWSOutpostsservers', 'Outposts Servers', 'Compute'],
  ['AWSParallelCluster', 'ParallelCluster', 'Compute'],
  ['AWSParallelComputingService', 'Parallel Computing Service', 'Compute'],
  ['AWSServerlessApplicationRepository', 'Serverless Application Repository', 'Compute'],
  ['AWSSimSpaceWeaver', 'SimSpace Weaver', 'Compute'],
  ['AWSWavelength', 'Wavelength', 'Compute'],
  ['ElasticFabricAdapter', 'Elastic Fabric Adapter', 'Compute'],
  // ---- Containers ----
  ['AmazonECSAnywhere', 'ECS Anywhere', 'Containers'],
  ['AmazonEKSAnywhere', 'EKS Anywhere', 'Containers'],
  ['AmazonEKSDistro', 'EKS Distro', 'Containers'],
  ['Bottlerocket', 'Bottlerocket', 'Containers'],
  ['RedHatOpenShiftServiceonAWS', 'Red Hat OpenShift Service (ROSA)', 'Containers'],
  // ---- Networking ----
  ['AmazonApplicationRecoveryController', 'Application Recovery Controller', 'Networking'],
  ['AmazonVirtualPrivateCloud', 'VPC', 'Networking'],
  ['AmazonVPCLattice', 'VPC Lattice', 'Networking'],
  ['AWSAppMesh', 'App Mesh', 'Networking'],
  ['AWSClientVPN', 'Client VPN', 'Networking'],
  ['AWSCloudMap', 'Cloud Map', 'Networking'],
  ['AWSCloudWAN', 'Cloud WAN', 'Networking'],
  ['AWSDirectConnect', 'Direct Connect', 'Networking'],
  ['AWSGlobalAccelerator', 'Global Accelerator', 'Networking'],
  ['AWSPrivateLink', 'PrivateLink', 'Networking'],
  ['AWSRTBFabric', 'RTB Fabric', 'Networking'],
  ['AWSSitetoSiteVPN', 'Site-to-Site VPN', 'Networking'],
  ['AWSTelcoNetworkBuilder', 'Telco Network Builder', 'Networking'],
  ['AWSTransitGateway', 'Transit Gateway', 'Networking'],
  ['ElasticLoadBalancing', 'Elastic Load Balancing', 'Networking'],
  // ---- Storage ----
  ['AmazonElasticBlockStore', 'EBS', 'Storage'],
  ['AmazonFileCache', 'File Cache', 'Storage'],
  ['AmazonFSx', 'FSx', 'Storage'],
  ['AmazonFSxforLustre', 'FSx for Lustre', 'Storage'],
  ['AmazonFSxforNetAppONTAP', 'FSx for NetApp ONTAP', 'Storage'],
  ['AmazonFSxforOpenZFS', 'FSx for OpenZFS', 'Storage'],
  ['AmazonFSxforWFS', 'FSx for Windows File Server', 'Storage'],
  ['AmazonS3onOutposts', 'S3 on Outposts', 'Storage'],
  ['AmazonSimpleStorageServiceGlacier', 'S3 Glacier', 'Storage'],
  ['AWSBackintAgent', 'Backint Agent', 'Storage'],
  ['AWSElasticDisasterRecovery', 'Elastic Disaster Recovery', 'Storage'],
  ['AWSSnowball', 'Snowball', 'Storage'],
  ['AWSSnowballEdge', 'Snowball Edge', 'Storage'],
  ['AWSStorageGateway', 'Storage Gateway', 'Storage'],
  // ---- Database ----
  ['AmazonDocumentDB', 'DocumentDB', 'Database'],
  ['AmazonKeyspaces', 'Keyspaces', 'Database'],
  ['AmazonMemoryDB', 'MemoryDB', 'Database'],
  ['AmazonNeptune', 'Neptune', 'Database'],
  ['AmazonTimestream', 'Timestream', 'Database'],
  ['OracleDatabaseatAWS', 'Oracle Database at AWS', 'Database'],
  // ---- Security ----
  ['AmazonCloudDirectory', 'Cloud Directory', 'Security'],
  ['AmazonDetective', 'Detective', 'Security'],
  ['AmazonInspector', 'Inspector', 'Security'],
  ['AmazonMacie', 'Macie', 'Security'],
  ['AmazonSecurityLake', 'Security Lake', 'Security'],
  ['AmazonVerifiedPermissions', 'Verified Permissions', 'Security'],
  ['AWSArtifact', 'Artifact', 'Security'],
  ['AWSAuditManager', 'Audit Manager', 'Security'],
  ['AWSCloudHSM', 'CloudHSM', 'Security'],
  ['AWSDirectoryService', 'Directory Service', 'Security'],
  ['AWSFirewallManager', 'Firewall Manager', 'Security'],
  ['AWSIAMIdentityCenter', 'IAM Identity Center', 'Security'],
  ['AWSIdentityandAccessManagement', 'IAM', 'Security'],
  ['AWSNetworkFirewall', 'Network Firewall', 'Security'],
  ['AWSPaymentCryptography', 'Payment Cryptography', 'Security'],
  ['AWSPrivateCertificateAuthority', 'Private Certificate Authority', 'Security'],
  ['AWSResourceAccessManager', 'Resource Access Manager', 'Security'],
  ['AWSSecurityAgent', 'Security Agent', 'Security'],
  ['AWSSecurityHub', 'Security Hub', 'Security'],
  ['AWSSecurityIncidentResponse', 'Security Incident Response', 'Security'],
  ['AWSShield', 'Shield', 'Security'],
  ['AWSSigner', 'Signer', 'Security'],
  ['AWSVerifiedAccess', 'Verified Access', 'Security'],
  // ---- App Integration ----
  ['AmazonAppFlow', 'AppFlow', 'App Integration'],
  ['AmazonManagedWorkflowsforApacheAirflow', 'Managed Workflows for Apache Airflow', 'App Integration'],
  ['AmazonMQ', 'Amazon MQ', 'App Integration'],
  ['AWSB2BDataInterchange', 'B2B Data Interchange', 'App Integration'],
  ['AWSExpressWorkflows', 'Step Functions Express Workflows', 'App Integration'],
  // ---- Analytics ----
  ['AmazonCloudSearch', 'CloudSearch', 'Analytics'],
  ['AmazonDataFirehose', 'Data Firehose', 'Analytics'],
  ['AmazonDataZone', 'DataZone', 'Analytics'],
  ['AmazonEMR', 'EMR', 'Analytics'],
  ['AmazonFinSpace', 'FinSpace', 'Analytics'],
  ['AmazonManagedServiceforApacheFlink', 'Managed Service for Apache Flink', 'Analytics'],
  ['AmazonQuickSuite', 'Quick Suite', 'Analytics'],
  ['AWSCleanRooms', 'Clean Rooms', 'Analytics'],
  ['AWSDataExchange', 'Data Exchange', 'Analytics'],
  ['AWSEntityResolution', 'Entity Resolution', 'Analytics'],
  ['AWSGlueDataBrew', 'Glue DataBrew', 'Analytics'],
  ['AWSLakeFormation', 'Lake Formation', 'Analytics'],
  // ---- Machine Learning ----
  ['AmazonAugmentedAIA2I', 'Augmented AI (A2I)', 'Machine Learning'],
  ['AmazonBedrockAgentCore', 'Bedrock AgentCore', 'Machine Learning'],
  ['AmazonComprehend', 'Comprehend', 'Machine Learning'],
  ['AmazonElasticInference', 'Elastic Inference', 'Machine Learning'],
  ['AmazonForecast', 'Forecast', 'Machine Learning'],
  ['AmazonFraudDetector', 'Fraud Detector', 'Machine Learning'],
  ['AmazonKendra', 'Kendra', 'Machine Learning'],
  ['AmazonLex', 'Lex', 'Machine Learning'],
  ['AmazonLookoutforEquipment', 'Lookout for Equipment', 'Machine Learning'],
  ['AmazonLookoutforVision', 'Lookout for Vision', 'Machine Learning'],
  ['AmazonNova', 'Nova', 'Machine Learning'],
  ['AmazonPersonalize', 'Personalize', 'Machine Learning'],
  ['AmazonPolly', 'Polly', 'Machine Learning'],
  ['AmazonQ', 'Amazon Q', 'Machine Learning'],
  ['AmazonRekognition', 'Rekognition', 'Machine Learning'],
  ['AmazonSageMakerAI', 'SageMaker AI', 'Machine Learning'],
  ['AmazonSageMakerGroundTruth', 'SageMaker Ground Truth', 'Machine Learning'],
  ['AmazonSageMakerStudioLab', 'SageMaker Studio Lab', 'Machine Learning'],
  ['AmazonTextract', 'Textract', 'Machine Learning'],
  ['AmazonTranscribe', 'Transcribe', 'Machine Learning'],
  ['AmazonTranslate', 'Translate', 'Machine Learning'],
  ['ApacheMXNetonAWS', 'Apache MXNet on AWS', 'Machine Learning'],
  ['AWSDeepLearningAMIs', 'Deep Learning AMIs', 'Machine Learning'],
  ['AWSDeepLearningContainers', 'Deep Learning Containers', 'Machine Learning'],
  ['AWSDeepRacer', 'DeepRacer', 'Machine Learning'],
  ['AWSNeuron', 'Neuron', 'Machine Learning'],
  ['AWSPanorama', 'Panorama', 'Machine Learning'],
  ['PyTorchonAWS', 'PyTorch on AWS', 'Machine Learning'],
  ['TensorFlowonAWS', 'TensorFlow on AWS', 'Machine Learning'],
  // ---- Healthcare ----
  ['AmazonComprehendMedical', 'Comprehend Medical', 'Healthcare'],
  ['AWSHealthImaging', 'HealthImaging', 'Healthcare'],
  ['AWSHealthLake', 'HealthLake', 'Healthcare'],
  ['AWSHealthOmics', 'HealthOmics', 'Healthcare'],
  ['AWSHealthScribe', 'HealthScribe', 'Healthcare'],
  // ---- IoT ----
  ['AmazonMonitron', 'Monitron', 'IoT'],
  ['AWSIoTDeviceDefender', 'IoT Device Defender', 'IoT'],
  ['AWSIoTDeviceManagement', 'IoT Device Management', 'IoT'],
  ['AWSIoTEvents', 'IoT Events', 'IoT'],
  ['AWSIoTExpressLink', 'IoT ExpressLink', 'IoT'],
  ['AWSIoTFleetWise', 'IoT FleetWise', 'IoT'],
  ['AWSIoTGreengrass', 'IoT Greengrass', 'IoT'],
  ['AWSIoTSiteWise', 'IoT SiteWise', 'IoT'],
  ['AWSIoTTwinMaker', 'IoT TwinMaker', 'IoT'],
  ['FreeRTOS', 'FreeRTOS', 'IoT'],
  // ---- Management ----
  ['AmazonManagedGrafana', 'Managed Grafana', 'Management'],
  ['AmazonManagedServiceforPrometheus', 'Managed Service for Prometheus', 'Management'],
  ['AWSAppConfig', 'AppConfig', 'Management'],
  ['AWSApplicationAutoScaling', 'Application Auto Scaling', 'Management'],
  ['AWSAutoScaling', 'AWS Auto Scaling', 'Management'],
  ['AWSChatbot', 'Chatbot', 'Management'],
  ['AWSCloudControlAPI', 'Cloud Control API', 'Management'],
  ['AWSCloudFormation', 'CloudFormation', 'Management'],
  ['AWSComputeOptimizer', 'Compute Optimizer', 'Management'],
  ['AWSConsoleMobileApplication', 'Console Mobile Application', 'Management'],
  ['AWSControlTower', 'Control Tower', 'Management'],
  ['AWSDistroforOpenTelemetry', 'Distro for OpenTelemetry', 'Management'],
  ['AWSFaultInjectionService', 'Fault Injection Service', 'Management'],
  ['AWSHealthDashboard', 'Health Dashboard', 'Management'],
  ['AWSLaunchWizard', 'Launch Wizard', 'Management'],
  ['AWSLicenseManager', 'License Manager', 'Management'],
  ['AWSManagementConsole', 'Management Console', 'Management'],
  ['AWSOrganizations', 'Organizations', 'Management'],
  ['AWSProton', 'Proton', 'Management'],
  ['AWSResilienceHub', 'Resilience Hub', 'Management'],
  ['AWSResourceExplorer', 'Resource Explorer', 'Management'],
  ['AWSServiceCatalog', 'Service Catalog', 'Management'],
  ['AWSServiceManagementConnector', 'Service Management Connector', 'Management'],
  ['AWSSystemsManager', 'Systems Manager', 'Management'],
  ['AWSTrustedAdvisor', 'Trusted Advisor', 'Management'],
  ['AWSUserNotifications', 'User Notifications', 'Management'],
  ['AWSWellArchitectedTool', 'Well-Architected Tool', 'Management'],
  // ---- Developer Tools ----
  ['AmazonCodeCatalyst', 'CodeCatalyst', 'Developer Tools'],
  ['AmazonCodeGuru', 'CodeGuru', 'Developer Tools'],
  ['AmazonCodeWhisperer', 'CodeWhisperer', 'Developer Tools'],
  ['AmazonCorretto', 'Corretto', 'Developer Tools'],
  ['AmazonDevOpsGuru', 'DevOps Guru', 'Developer Tools'],
  ['AWSCloud9', 'Cloud9', 'Developer Tools'],
  ['AWSCloudDevelopmentKit', 'CDK', 'Developer Tools'],
  ['AWSCloudShell', 'CloudShell', 'Developer Tools'],
  ['AWSCodeArtifact', 'CodeArtifact', 'Developer Tools'],
  ['AWSCodeBuild', 'CodeBuild', 'Developer Tools'],
  ['AWSCodeCommit', 'CodeCommit', 'Developer Tools'],
  ['AWSCodeDeploy', 'CodeDeploy', 'Developer Tools'],
  ['AWSCodePipeline', 'CodePipeline', 'Developer Tools'],
  ['AWSCommandLineInterface', 'CLI', 'Developer Tools'],
  ['AWSDevOpsAgent', 'DevOps Agent', 'Developer Tools'],
  ['AWSInfrastructureComposer', 'Infrastructure Composer', 'Developer Tools'],
  ['AWSToolsandSDKs', 'Tools and SDKs', 'Developer Tools'],
  // ---- Migration ----
  ['AWSApplicationDiscoveryService', 'Application Discovery Service', 'Migration'],
  ['AWSApplicationMigrationService', 'Application Migration Service', 'Migration'],
  ['AWSDatabaseMigrationService', 'Database Migration Service', 'Migration'],
  ['AWSDataSync', 'DataSync', 'Migration'],
  ['AWSDataTransferTerminal', 'Data Transfer Terminal', 'Migration'],
  ['AWSMainframeModernization', 'Mainframe Modernization', 'Migration'],
  ['AWSMigrationEvaluator', 'Migration Evaluator', 'Migration'],
  ['AWSMigrationHub', 'Migration Hub', 'Migration'],
  ['AWSTransferFamily', 'Transfer Family', 'Migration'],
  ['AWSTransform', 'Transform', 'Migration'],
  // ---- Media ----
  ['AmazonInteractiveVideoService', 'Interactive Video Service', 'Media'],
  ['AmazonKinesisVideoStreams', 'Kinesis Video Streams', 'Media'],
  ['AWSDeadlineCloud', 'Deadline Cloud', 'Media'],
  ['AWSElementalAppliancesSoftware', 'Elemental Appliances & Software', 'Media'],
  ['AWSElementalConductor', 'Elemental Conductor', 'Media'],
  ['AWSElementalDelta', 'Elemental Delta', 'Media'],
  ['AWSElementalLink', 'Elemental Link', 'Media'],
  ['AWSElementalLive', 'Elemental Live', 'Media'],
  ['AWSElementalMediaConnect', 'Elemental MediaConnect', 'Media'],
  ['AWSElementalMediaConvert', 'Elemental MediaConvert', 'Media'],
  ['AWSElementalMediaLive', 'Elemental MediaLive', 'Media'],
  ['AWSElementalMediaPackage', 'Elemental MediaPackage', 'Media'],
  ['AWSElementalMediaStore', 'Elemental MediaStore', 'Media'],
  ['AWSElementalMediaTailor', 'Elemental MediaTailor', 'Media'],
  ['AWSElementalServer', 'Elemental Server', 'Media'],
  ['AWSThinkboxDeadline', 'Thinkbox Deadline', 'Media'],
  ['AWSThinkboxFrost', 'Thinkbox Frost', 'Media'],
  ['AWSThinkboxKrakatoa', 'Thinkbox Krakatoa', 'Media'],
  ['AWSThinkboxStoke', 'Thinkbox Stoke', 'Media'],
  ['AWSThinkboxXMesh', 'Thinkbox XMesh', 'Media'],
  // ---- Business Apps ----
  ['AmazonChime', 'Chime', 'Business Apps'],
  ['AmazonChimeSDK', 'Chime SDK', 'Business Apps'],
  ['AmazonConnect', 'Connect', 'Business Apps'],
  ['AmazonPinpoint', 'Pinpoint', 'Business Apps'],
  ['AmazonPinpointAPIs', 'Pinpoint APIs', 'Business Apps'],
  ['AmazonWorkDocs', 'WorkDocs', 'Business Apps'],
  ['AmazonWorkDocsSDK', 'WorkDocs SDK', 'Business Apps'],
  ['AmazonWorkMail', 'WorkMail', 'Business Apps'],
  ['AWSAppFabric', 'AppFabric', 'Business Apps'],
  ['AWSEndUserMessaging', 'End User Messaging', 'Business Apps'],
  ['AWSSupplyChain', 'Supply Chain', 'Business Apps'],
  ['AWSWickr', 'Wickr', 'Business Apps'],
  // ---- Front-End & Mobile ----
  ['AmazonLocationService', 'Location Service', 'Front-End & Mobile'],
  ['AWSAmplify', 'Amplify', 'Front-End & Mobile'],
  ['AWSAppStudio', 'App Studio', 'Front-End & Mobile'],
  ['AWSDeviceFarm', 'Device Farm', 'Front-End & Mobile'],
  // ---- End User Computing ----
  ['AmazonDCV', 'DCV', 'End User Computing'],
  ['AmazonWorkSpaces', 'WorkSpaces', 'End User Computing'],
  // ---- Cost Management ----
  ['AWSBillingConductor', 'Billing Conductor', 'Cost Management'],
  ['AWSBudgets', 'Budgets', 'Cost Management'],
  ['AWSCostandUsageReport', 'Cost and Usage Report', 'Cost Management'],
  ['AWSCostExplorer', 'Cost Explorer', 'Cost Management'],
  ['ReservedInstanceReporting', 'Reserved Instance Reporting', 'Cost Management'],
  ['SavingsPlans', 'Savings Plans', 'Cost Management'],
  // ---- Games / Quantum / Blockchain / Satellite ----
  ['AmazonGameLiftServers', 'GameLift Servers', 'Games'],
  ['AmazonGameLiftStreams', 'GameLift Streams', 'Games'],
  ['Open3DEngine', 'Open 3D Engine', 'Games'],
  ['AmazonBraket', 'Braket', 'Quantum'],
  ['AmazonManagedBlockchain', 'Managed Blockchain', 'Blockchain'],
  ['AWSGroundStation', 'Ground Station', 'Satellite'],
  // ---- Support & Enablement ----
  ['AWSActivate', 'Activate', 'Support & Enablement'],
  ['AWSIQ', 'IQ', 'Support & Enablement'],
  ['AWSManagedServices', 'Managed Services (AMS)', 'Support & Enablement'],
  ['AWSMarketplace', 'Marketplace', 'Support & Enablement'],
  ['AWSPartnerCentral', 'Partner Central', 'Support & Enablement'],
  ['AWSProfessionalServices', 'Professional Services', 'Support & Enablement'],
  ['AWSrePost', 're:Post', 'Support & Enablement'],
  ['AWSrePostPrivate', 're:Post Private', 'Support & Enablement'],
  ['AWSSupport', 'Support', 'Support & Enablement'],
  ['AWSTrainingCertification', 'Training & Certification', 'Support & Enablement'],
];

const entries = manifest as Record<string, { file: string; color: string }>;

function accentFor(file: string): string {
  return entries[file.toLowerCase()]?.color ?? '#FF9900';
}

function slug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

export const AWS_EXTENDED_SERVICES: ServiceDef[] = EXTENDED.map(([file, name, category]) => ({
  id: `aws-${slug(name)}`,
  name,
  provider: 'aws' as const,
  category,
  icon: 'Box',
  iconUrl: `/icons/aws/svc/${file}.svg`,
  accent: accentFor(file),
  blurb: `${category} — indicative pricing, edit the monthly cost.`,
  fields: [{ key: 'monthlyCost', label: 'Est. monthly cost', type: 'number' as const, unit: 'USD', default: 0 }],
  estimate: (c) => {
    const v = c.monthlyCost;
    const n = typeof v === 'number' ? v : parseFloat(String(v ?? ''));
    return Number.isFinite(n) ? n : 0;
  },
}));

/** Icon files claimed by the extended list (coverage-test support). */
export const EXTENDED_ICON_FILES: string[] = EXTENDED.map(([file]) => file);
